name: "Upload GitHub Action workflows logs to elastic"
description: "Downloads the workflow logs and uploads to Elastic"
author: "Shahar Glazner"
inputs:
  github_token:
    description: "GitHub PAT"
  github_org:
    description: "The github organization to read the workflows logs from"
  github_repository:
    description: "The github repository to read the workflows logs from"
  github_run_id:
    description: "The workflow specific run id to read the logs from"
  elastic_api_key_id:
    description: "Elastic api key id"
  elastic_api_key:
    description: "Elastic api key"
  elastic_host:
    description: "The elastic host"
    default: "http://localhost:9200"
  elastic_index:
    description: "The elastic index"

outputs:
  result:
    description: "Result"

runs:
  using: "composite"
  steps:
    - run: |
        echo "GITHUBREPO: $INPUT_GITHUB_REPOSITORY"
        echo "GITHUBTOKEN: $INPUT_GITHUB_TOKEN"
        echo "GITHUBORG: $INPUT_GITHUB_ORG"
        echo "GITHUBRUNID: $INPUT_GITHUB_RUN_ID"
      shell: bash
      env:
        INPUT_GITHUB_REPOSITORY: ${{ inputs.github_repository }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_GITHUB_ORG: ${{ inputs.github_org }}
        INPUT_GITHUB_RUN_ID: ${{ inputs.github_run_id }}
    - run: |
       cd $GITHUB_ACTION_PATH && pip3 install -r requirements.txt
      shell: bash
    - run: |
       cd $GITHUB_ACTION_PATH && python3 main.py
      shell: bash

